### PR TITLE
Add html visualization

### PR DESCRIPTION
**Pull request by gurgentus**
The best way I could figure out to integrate the plots with the tests was to incorporate them into an html report generated by pytest-html plugin.  Added the files needed for pytest-html.  Currently the plots are generated in the 'testplots' subdirectory in the directory where pytest is run with:

pytest -vvvv --html=report.html

Also created index.html with a link to the report.html assuming it is generated in the top directory.  If GitHub Pages is enabled from Settings https://[username].github.io/acc/ will render index.html with a link to report.html.

This is not an elegant solution by any means, so any suggestions for improvement are welcome!  There is a big side-effect of having to add all of the generated plots to GitHub version control. On the plus side the generated test report can be viewed easily from a GitHub repository.  Let me know if there are any suggestions to make this more robust and I can incorporate them into the pull request!

### CODE REVIEW

**Comment by ingenieroariel** [comment]
Thanks @gurgentus.

I see the following output in the tests results:

```INTERNALERROR>   File "/home/travis/build/autti/acc/acc/tests/conftest.py", line 13, in pytest_runtest_makereport
INTERNALERROR>     extra.append(pytest_html.extras.html('<div> Details </div>'))
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'extras'```

Do you know what could be going on? Can you amend .travis.yml to install any new dependencies for testing?

**Comment by gurgentus** [comment]
Yes, my bad, had forgotten to add the pytest-html dependency.  Thanks!

**Comment by gurgentus** [comment]
I think it should be ok now.

**Comment by ingenieroariel** [comment]
@gurgentus can you leave the tests results out? I think it is better if we publish the test results to the gh-pages branch after each commit instead of directly to master.

**Comment by gurgentus** [comment]
@ingenieroariel Sure, done!

**Comment by ingenieroariel** [comment]
Thanks! We are still getting errors but I think it is unrelated to this PR. I'll merge and fix afterwards.

**Pull request merged**
